### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by githubteacher** [githubschool/teachers#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'Unwatch' button and selecting either the 'Not watching' or 'Ignoring' option.

**Comment by arorasudhir** [comment]
Add me 👍

**Comment by crstexas** [comment]
Please add me to this awesome project.

**Comment by nitareddy** [comment]
Test by Nita

**Comment by trshqo** [comment]
Bob's Burgers is overrated

**Comment by johnCody72** [comment]
here i am

**Comment by yalinluo** [comment]
:)

**Comment by jackieserio** [comment]
test

**Comment by mikeressel** [comment]
Add me :)

**Comment by flighteureka** [comment]
Test II

**Comment by nbErnie** [comment]
howdy

**Comment by CodesAway** [comment]
Amy 👍

**Comment by smithcb2** [comment]
Add

**Comment by CodesAway** [comment]
👎

**Comment by gloppyuser** [comment]
hello

**Comment by steampunkroller** [comment]
good morning!

**Comment by CodesAway** [comment]
🍕

**Comment by CodesAway** [comment]
🇹🇷 S

**Comment by Mahitha189** [comment]
GM!

**Comment by crstexas** [comment]
@beardofedu

**Comment by trshqo** [comment]
@mikeressel

**Comment by crstexas** [comment]
@beardofedu

**Comment by jackieserio** [comment]
> Add me 👍

test test test

**Comment by trsrmartin** [comment]
Comment

**Comment by shubhijagmohan** [comment]
Hi

**Comment by cnicholas537** [comment]
Hey

**Comment by jtomclayton** [comment]
Hello World

**Comment by robbuscha** [comment]
Rob is in

**Comment by Aruna848** [comment]
Test
