### ISSUE TITLE
Set Protection on Master and Development Branches

### ISSUE THREAD

**Issue by trsrmartin** [githubschool/teachers#43]

**Comment by beargle** [comment]
@cnicholas537 volunteered to take this

**Comment by beargle** [comment]
@mikeressel can review before closing

**Comment by cnicholas537** [comment]
Why me?

**Comment by johnCody72** [comment]
@cnicholas537 The development branch is created, so you can go ahead and set protections on it. #42

**Comment by cnicholas537** [comment]
Done, maybe
